FORMAT: 1A
HOST: https://example.com/

# YOURLS

# Group Short URL

## Create short URL [/shorturl]
With this API method you can create a short URL with YOURLS.
We are using the software YOURLS (version 1.7.1) with some adaptions.

### POST
Please refer to the YOURLS API documentation for more details: https://yourls.org/#API
We changed some things for our custom API. These changes are shown here.
You need to use POST since GET is not supported anymore.

+ Attributes
  + signature (string) -  This is the API key class S that can be requested via email.
  + timestamp (number) - An API key class S is valid for a limited time (currently for 6 months). You have to pass this parameter with the timestamp you got from us with your API key.
  + action (string) -  Use `shorturl` to get short URL for a link.
  + url (string) -  The link to shorten (like `https://example.com/abc/`). You can use this API only for links from our website.
  + output (string) -  The output format: either `json`, `xml` or `simple`.

+ Request (application/x-www-form-urlencoded)

+ Response 200 (application/json)
This is an example JSON response.

    + Body

            {
            "status": "success",
            "message": "https://example.com/abc/ added to database",
            "title": "Demo Link",
            "shorturl": "https://example.com/demo",
            "statusCode": 200
            }


## View short URL [/shorturl]
With this API method you can view the long URL from a shortened link with YOURLS.
We are using the software YOURLS (version 1.7.1) with some adaptions.

### POST
Please refer to the YOURLS API documentation for more details: https://yourls.org/#API
We changed some things for our custom API. These changes are shown here.
You need to use POST since GET is not supported anymore.

+ Attributes
  + signature (string) -  This is the API key class S that can be requested via email.
  + timestamp (number) - An API key class S is valid for a limited time (currently for 6 months). You have to pass this parameter with the timestamp you got from us with your API key.
  + action (string) -  Use `expand` to get long URL of a shorturl.
  + shorturl (string) -  The short URL to expand (can be either `demo` or `https://example.com/demo`).
  + output (string) -  The output format: either `json`, `xml` or `simple`.

+ Request (application/x-www-form-urlencoded)

+ Response 200 (application/json)
This is an example response.

    + Body

            {
            "keyword": "demo",
            "shorturl": "https://example.com/demo",
            "longurl": "https://example.com/abc/",
            "message": "success",
            "statusCode": 200
            }
